services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
      - /workspace/frontend/node_modules
      - /workspace/backend/venv
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MONGODB_URL=mongodb://mongodb:27017
      - DATABASE_NAME=red_pandas_db
    command: sleep infinity
    network_mode: service:mongodb
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=red_pandas_db
    ports:
      - '27018:27017'

volumes:
  mongodb-data:
